// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDtL-gOzKOYZ2KPAy_MKVGXkFLL1rbhR4',
    appId: '1:772175119710:web:4585d855632f3943b5fbcf',
    messagingSenderId: '772175119710',
    projectId: 'demoapp-39cc1',
    authDomain: 'demoapp-39cc1.firebaseapp.com',
    storageBucket: 'demoapp-39cc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAieXzcV0RdVXCIj4h9UvY-pF-SnuzWf6w',
    appId: '1:772175119710:android:3fd8ffbad50d2dbdb5fbcf',
    messagingSenderId: '772175119710',
    projectId: 'demoapp-39cc1',
    storageBucket: 'demoapp-39cc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFFWJltt3hWpGE-cW2nyls23BDjLZSusU',
    appId: '1:772175119710:ios:be5a72808a070e30b5fbcf',
    messagingSenderId: '772175119710',
    projectId: 'demoapp-39cc1',
    storageBucket: 'demoapp-39cc1.appspot.com',
    iosBundleId: 'com.example.demoapp',
  );
}
